import{FaceLandmarker,FilesetResolver}from"https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/+esm";
const $=s=>document.querySelector(s),video=$("#video"),canvas=$("#overlay"),ctx=canvas.getContext("2d");
let landmarker,stream,mode="healthy",running=false,last=0;
async function initAI(){const vision=await FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm");landmarker=await FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:"https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task",delegate:"GPU"},runningMode:"VIDEO",numFaces:1});}
async function start(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();$("#home").classList.remove("active");$("#cameraScreen").classList.add("active");$("#status").textContent="Loading face tracking…";await initAI();running=true;requestAnimationFrame(loop)}catch(e){alert("Camera couldn't start. Please allow camera access and try again.");}}
function stop(){running=false;stream?.getTracks().forEach(t=>t.stop());$("#cameraScreen").classList.remove("active");$("#home").classList.add("active")}
function loop(t){if(!running)return;if(video.readyState>=2&&landmarker&&t-last>33){last=t;canvas.width=video.videoWidth;canvas.height=video.videoHeight;ctx.clearRect(0,0,canvas.width,canvas.height);const r=landmarker.detectForVideo(video,t);if(r.faceLandmarks?.length){$("#status").textContent="Face found ✓";draw(r.faceLandmarks[0],t)}else $("#status").textContent="Finding face…"}requestAnimationFrame(loop)}
function draw(lm,t){if(mode==="healthy")return;const ids=[61,146,91,181,84,17,314,405,321,375,291,308,324,318,402,317,14,87,178,88,95,78,191,80,81,82,13,312,311,310,415];
const pts=ids.map(i=>({x:lm[i].x*canvas.width,y:lm[i].y*canvas.height}));ctx.save();ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.clip();
const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),x=Math.min(...xs),y=Math.min(...ys),w=Math.max(...xs)-x,h=Math.max(...ys)-y;
ctx.fillStyle=mode==="cavity"?"rgba(55,32,18,.48)":"rgba(170,125,35,.34)";ctx.fillRect(x,y,w,h);
const count=mode==="cavity"?10:6;for(let i=0;i<count;i++){const px=x+w*(.1+((i*37)%80)/100),py=y+h*(.2+((i*53)%60)/100),r=Math.max(2,w*(mode==="cavity"?.018:.012));ctx.beginPath();ctx.arc(px,py,r,0,Math.PI*2);ctx.fillStyle=mode==="cavity"?"#25150e":"#8c681c";ctx.fill()}
if(mode==="cavity"){const wx=x+w*(.5+.28*Math.sin(t/420)),wy=y+h*(.55+.18*Math.cos(t/300));ctx.strokeStyle="#d9d08b";ctx.lineWidth=Math.max(3,w*.018);ctx.lineCap="round";ctx.beginPath();ctx.moveTo(wx-w*.05,wy);ctx.quadraticCurveTo(wx,wy-h*.22,wx+w*.06,wy);ctx.stroke()}ctx.restore()}
$("#start").onclick=start;$("#back").onclick=stop;document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>{document.querySelectorAll(".mode").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.mode});
$("#rescue").onclick=()=>{mode="healthy";document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x.dataset.mode==="healthy"));canvas.classList.add("flash");$("#guide").textContent="✨ Teeth saved! Great brushing!";setTimeout(()=>{canvas.classList.remove("flash");$("#guide").textContent="Smile & show your teeth 😁"},1800)};